// <auto-generated />
using GeekyMoney.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GeekyMoney.Data.Migrations
{
    [DbContext(typeof(GeekyMoneyContext))]
    [Migration("20170924185755_InitialStabAtIt")]
    partial class InitialStabAtIt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeekyMoney.Data.DTO.Fee", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeductible");

                    b.Property<string>("Name");

                    b.Property<Guid?>("RealEstatePropertyID");

                    b.Property<int>("ScheduleTypeID");

                    b.HasKey("ID");

                    b.HasIndex("RealEstatePropertyID");

                    b.ToTable("Fee");
                });

            modelBuilder.Entity("GeekyMoney.Data.DTO.RealEstateProperty", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AppreciationRate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsMultiUnit");

                    b.Property<string>("MLSID");

                    b.Property<string>("Name");

                    b.Property<double>("OccupancyRate");

                    b.Property<decimal>("PropertyTaxAmount");

                    b.Property<decimal>("PropertyTaxRate");

                    b.Property<decimal>("PropertyValue");

                    b.Property<Guid?>("RealEstatePropertyID");

                    b.HasKey("ID");

                    b.HasIndex("RealEstatePropertyID");

                    b.ToTable("RealEstateProperty");
                });

            modelBuilder.Entity("GeekyMoney.Data.DTO.RentalRate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<Guid?>("RealEstatePropertyID");

                    b.Property<decimal>("RentalAmount");

                    b.Property<int>("ScheduleTypeID");

                    b.HasKey("ID");

                    b.HasIndex("RealEstatePropertyID");

                    b.ToTable("RentalRate");
                });

            modelBuilder.Entity("GeekyMoney.Data.DTO.Fee", b =>
                {
                    b.HasOne("GeekyMoney.Data.DTO.RealEstateProperty")
                        .WithMany("PropertyFees")
                        .HasForeignKey("RealEstatePropertyID");
                });

            modelBuilder.Entity("GeekyMoney.Data.DTO.RealEstateProperty", b =>
                {
                    b.HasOne("GeekyMoney.Data.DTO.RealEstateProperty")
                        .WithMany("Units")
                        .HasForeignKey("RealEstatePropertyID");
                });

            modelBuilder.Entity("GeekyMoney.Data.DTO.RentalRate", b =>
                {
                    b.HasOne("GeekyMoney.Data.DTO.RealEstateProperty")
                        .WithMany("RentSchedules")
                        .HasForeignKey("RealEstatePropertyID");
                });
#pragma warning restore 612, 618
        }
    }
}
